### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by BraveSirRobin** [cbrichford/docker-ipsec#2]
When running on RHEL7:

```
>>> import docker_ipsec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/python/devpkve/lib/python2.7/site-packages/docker_ipsec/__init__.py", line 1, in <module>
    from docker_ipsec.common import (IPSecInfo, DockerInfo, getInterfaceNameForIndex, installIPTablesRule, removeIPTablesRules, ipsec)
  File "/home/robin/python/devpkve/lib/python2.7/site-packages/docker_ipsec/common.py", line 153
    def ipsec(*args, verbose=False):
```

The args to the ipsec function are in the wrong order.

**Comment by cbrichford** [comment]
@BraveSirRobin python 2.X is not supported.  Try python3.
