### ISSUE TITLE
JSON import error

### ISSUE THREAD

**Issue by BraveSirRobin** [cbrichford/docker-ipsec#3]
When running on RHEL7:

```
>>> import docker_ipsec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/python/devpkve/lib/python2.7/site-packages/docker_ipsec/__init__.py", line 1, in <module>
    from docker_ipsec.common import (IPSecInfo, DockerInfo, getInterfaceNameForIndex, installIPTablesRule, removeIPTablesRules, ipsec)
  File "/home/robin/python/devpkve/lib/python2.7/site-packages/docker_ipsec/common.py", line 9, in <module>
    from json.decoder import JSONDecodeError
ImportError: cannot import name JSONDecodeError
```

**Comment by cbrichford** [comment]
Python 2.X is not supported.  Try python 3.
